# Generated by Django 3.1.7 on 2021-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210228_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
